# Generated by Django 4.2.23 on 2025-12-07 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('35', '5'), ('36', '6'), ('37', '7'), ('38', '8'), ('39', '9'), ('40', '10'), ('41', '11'), ('42', '12'), ('43', '13')], max_length=20)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='authapp.product')),
            ],
        ),
    ]
