# Generated by Django 4.2.23 on 2025-12-07 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_productvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='No image find', max_length=300)),
                ('variant', models.CharField(default='Default', max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.PositiveIntegerField()),
                ('total', models.IntegerField()),
                ('order', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, to='authapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.product')),
            ],
        ),
    ]
