# Generated by Django 4.2.23 on 2025-12-07 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authapp.productvariant'),
        ),
    ]
