# Generated by Django 4.2.23 on 2025-12-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_orderitem_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(max_length=30),
        ),
    ]
