# Generated by Django 4.2.23 on 2025-12-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_productvariant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='beads_name',
            field=models.CharField(default='unknown', max_length=150),
        ),
    ]
