# Generated by Django 4.2.23 on 2025-12-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_orderitem_beads_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='beads_name',
            field=models.CharField(blank=True, default='unknown', max_length=150, null=True),
        ),
    ]
