# Generated by Django 4.2.27 on 2025-12-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_orderitem_beads_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='customer_number',
            field=models.CharField(default='unknown', max_length=14),
        ),
    ]
